---
- name: restart dnsmasq
  systemd:
    name: dnsmasq
    state: restarted

- name: restart nginx
  systemd:
    name: nginx
    state: restarted

- name: reload firewalld
  systemd:
    name: firewalld
    state: reloaded
