[pxe_server]
# 사내망에 새로 생성한 PXE용 Ubuntu VM의 IP와 접속 계정 정보를 환경에 맞게 수정해주세요.
192.168.50.2 ansible_connection=ssh ansible_user=root ansible_password="VM_Password123!" ansible_ssh_common_args='-o StrictHostKeyChecking=no'
